package constant;

import java.util.Arrays;
import java.util.List;

public interface CommonConstants {
    String IMAGE_PATH_CHRUST = "C:\\Users\\Chrustkiran\\OneDrive\\Documents\\OCR\\image";
    String IMAGE_PATH_SARANGAN = "/home/sarangan/Desktop/step/";

    String CSV_PATH_CHRUST = "";
    String CSV_PATH_SARANGAN = "/home/sarangan/Desktop/se.csv";
    enum BUTTON_NAME {
        SAVE, PANEL1, PANEL2, PANEL3, CUSTOMER_ID, CARD_ISSUER_TYPE, CARD_LIMIT, AVERAGE_MONTHLY_USAGE,
        DOES_CREDIT_CARD_PROVIDE_LIFE_INSURANCE, AVERAGE_MONTHLY_PAYMENT, CARD_ISSUER_DATE, CARD_HOLDER_NAME,
        CARD_HOLDER_DOB, DOCKET_NO, REMARKS1, SEX1, RAGISTER_ADDRESS, CARD_TYPE, RATE_OF_INTEREST_TYPE,
        FICO_CREDIT_SCORE, CITY1, PROVINCE1, REMARK2, BENEFICIARY_NAME, ALTERNATE_ADDRESS, BENEFICIARY_DOB, CITY2, PROVINCE2,
        COUNTRY, BLOOD_GROUP, SEX2,CARD_EXPIRE_DATE,CREDIT_CARD_ACCOUNT_NUMBER,IDON_CUSTOMER_NUMBER,REMARK3
    }

    List<BUTTON_NAME> idFieldMap = Arrays.asList(BUTTON_NAME.CUSTOMER_ID, BUTTON_NAME.CARD_ISSUER_TYPE, BUTTON_NAME.CARD_LIMIT,
            BUTTON_NAME.AVERAGE_MONTHLY_USAGE,
            BUTTON_NAME.DOES_CREDIT_CARD_PROVIDE_LIFE_INSURANCE, BUTTON_NAME.AVERAGE_MONTHLY_PAYMENT,
            BUTTON_NAME.CARD_ISSUER_DATE, BUTTON_NAME.CARD_HOLDER_NAME,
            BUTTON_NAME.CARD_HOLDER_DOB, BUTTON_NAME.DOCKET_NO, BUTTON_NAME.REMARKS1, BUTTON_NAME.SEX1,
            BUTTON_NAME.RAGISTER_ADDRESS, BUTTON_NAME.CARD_TYPE, BUTTON_NAME.RATE_OF_INTEREST_TYPE,
            BUTTON_NAME.FICO_CREDIT_SCORE, BUTTON_NAME.CITY1, BUTTON_NAME.PROVINCE1, BUTTON_NAME.REMARK2,
            BUTTON_NAME.BENEFICIARY_NAME, BUTTON_NAME.ALTERNATE_ADDRESS, BUTTON_NAME.BENEFICIARY_DOB, BUTTON_NAME.CITY2,
            BUTTON_NAME.PROVINCE2,
            BUTTON_NAME.COUNTRY, BUTTON_NAME.BLOOD_GROUP, BUTTON_NAME.SEX2,
            BUTTON_NAME.CARD_EXPIRE_DATE,BUTTON_NAME.CREDIT_CARD_ACCOUNT_NUMBER,BUTTON_NAME.IDON_CUSTOMER_NUMBER,
            BUTTON_NAME.REMARK3);

    List<String> cardTypesprefix = Arrays.asList("Disc", "America", "Master", "PN", "other",
            "ohter", "Amb", "Ame", "discocer", "american", "Valiuym", "Bnka", "VALIUM", "Reteil", "azepam" ,"Lorazwpam",
            "Express", "gas", "Reia", "enetermine", "mater", "american");


    List<String> PHONE_NUMBER_STRINGS = Arrays.asList("phone number", "mobile", "phone", "tel", "telephone",
            "call", "sweet line");
}
